### ISSUE TITLE
发生异常FileNotFoundException

### ISSUE THREAD

**Issue by S-E-C** [Pixeval/Pixeval#312]
### Pixeval的版本

WinUI3

### 问题描述

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=系统找不到指定的文件。 (0x80070002)
  Source=Pixeval
  StackTrace:
   at Pixeval.AppManagement.AppContext.<GetIconAbsolutePath>d__18.MoveNext() in D:\respo\Pixeval\src\Pixeval\AppManagement\AppContext.cs:line 116
   at Pixeval.App.<OnLaunched>d__6.MoveNext() in D:\respo\Pixeval\src\Pixeval\App.xaml.cs:line 77

### 屏幕截图

![image](https://user-images.githubusercontent.com/59992930/229878366-a5b39f76-42e4-49f9-914e-604159c4032a.png)

### 错误代码

System.IO.FileNotFoundException

### Windows主要版本

Windows 11

### 具体Windows版本

Windows 11 22H2 (22621)

**Comment by Poker-sang** [comment]
如果下个版本出现可以重新打开这个议题
