### ISSUE TITLE
经常性闪退

### ISSUE THREAD

**Issue by wockkkk** [Pixeval/Pixeval#430]
### Pixeval的版本

WinUI3

### 问题描述

操作的快点就崩

### 错误代码

```
23:10:11 Error
UnobservedTaskException
at RegisterUnhandledExceptionHandler at C:\WorkSpace\Pixeval\src\Pixeval\App.xaml.cs: 152
	Type: System.AggregateException
	Source: 
	Message: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。. (i.pximg.net:443))
	StackTrace: 
		null
		Type: System.Net.Http.HttpRequestException
		Source: System.Net.Http
		Message: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。. (i.pximg.net:443)
		StackTrace: 
			   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
			   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
			   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
			   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
			   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
			   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
			   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
			Type: System.IO.IOException
			Source: System.Net.Sockets
			Message: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
			StackTrace: 
				   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
				   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
				   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
				   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
				   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
				   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
				   at Pixeval.CoreApi.Net.MakoHttpOptions.BypassedConnectCallback(SocketsHttpConnectionContext context, CancellationToken token)
				   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
				Type: System.Net.Sockets.SocketException
				Source: 
				Message: 远程主机强迫关闭了一个现有的连接。
				StackTrace: 
					null
```

### Windows主要版本

Windows 10

### 具体Windows版本

November 2021 Update/21H2 (19044)

**Comment by wockkkk** [comment]
[2024-04-17 23.log](https://github.com/Pixeval/Pixeval/files/15013168/2024-04-17.23.log)

**Comment by Poker-sang** [comment]
是快速切换图片的时候出现的问题吗

**Comment by Poker-sang** [comment]
开太多了确实会卡，内存我已经尽量释放了，但winui确实有这个问题

**Comment by Poker-sang** [comment]
卡顿问题在aot技术出来之后应该就能解决

**Comment by wockkkk** [comment]
是在加载图片和加载关注列表是闪退的

**Comment by Poker-sang** [comment]
我尽量已经拦截所有异常了，可能还是有漏网之鱼，我再检查一下

**Comment by gbwhisper** [comment]
待加载图片一多就会自动闪退。我就在想只加载Pid不进行预览是不是能更快点

**Comment by Poker-sang** [comment]
> 待加载图片一多就会自动闪退。我就在想只加载Pid不进行预览是不是能更快点

你可以提供日志吗，日志的问题是不是和这个issue的一样？

**Comment by wockkkk** [comment]
> 待加载图片一多就会自动闪退。我就在想只加载Pid不进行预览是不是能更快点

我觉得我和ta的问题一样

**Comment by wockkkk** [comment]
我在搜索的时候也是会崩，日志也一样

**Comment by Poker-sang** [comment]
初步分析是，在中止加载之后直接抛弃了加载线程，导致加载线程出现的异常没有被捕捉到，我会在下一次发布之前修复

**Comment by Poker-sang** [comment]
这个日志应该不是崩溃的原因

在崩溃的时候如果有日志的话，会以 **Critical** 标识而不是 **Error**。这是如果要查看日志可以到windows事件管理器查看（虽然看了也基本没啥用x）

估计可能是winui控件本身导致的崩溃，不过我还是会尽量排查别的地方的崩溃问题

**Comment by wockkkk** [comment]
[error.txt](https://github.com/Pixeval/Pixeval/files/15077798/error.txt)（这是windows事件管理器里的错误报告）
我找到了一个100%触发的复现方法：

在启动后加载“今日推荐”的图像时（显示“正在加载”）切到任意一个也要加载图像（显示“正在加载”）的页面就100%会闪退 报错也一样
![image](https://github.com/Pixeval/Pixeval/assets/167004757/f65c75f4-7cf8-4554-95b0-39291545a380)

**Comment by Apkeniqo** [comment]
遇到差不多的问题了。。。不过我是在打开收藏页面时闪退。。百分百触发

**Comment by Poker-sang** [comment]
> 遇到差不多的问题了。。。不过我是在打开收藏页面时闪退。。百分百触发

你的日志里能看的内容吗

**Comment by Poker-sang** [comment]
好像发现问题了【是网络不好的情况下可能出现的读取图片递归

**Comment by Poker-sang** [comment]
新版本里尝试修了一下这个问题】但因为我复现不了这个bug所以我不确定是否应该关闭这个issue

你可以试试看新的版本，如果闪退不怎么出现的话就可以关闭这个issue了】( ˙ε . )

**Comment by Apkeniqo** [comment]
> 新版本里尝试修了一下这个问题】但因为我复现不了这个bug所以我不确定是否应该关闭这个issue
> 
> 你可以试试看新的版本，如果闪退不怎么出现的话就可以关闭这个issue了】( ˙ε . )

感谢修复，不闪退了，但是下载路径的宏好像出问题了。。

**Comment by Poker-sang** [comment]
@Apkeniqo 只是改了路径宏的写法，导致不兼容旧的，你可以重置一下设置他就变为正确的了

**Comment by Apkeniqo** [comment]
> @Apkeniqo 只是改了路径宏的写法，导致不兼容旧的，你可以重置一下设置他就变为正确的了

这个倒不是大问题，主要是现在的宏设置时每输一个字母就会跳到第一位，应该是宏更新机制的问题吧？

**Comment by Poker-sang** [comment]
还真有这个问题，这应该认为是bug，我尽量下个小版本给修复了，你现在可以先通过复制粘贴来设置

**Comment by Poker-sang** [comment]
@Apkeniqo 已修复 via #473
