### ISSUE TITLE
每次登陆后自动闪退

### ISSUE THREAD

**Issue by chanmaoganda** [Pixeval/Pixeval#541]
### Pixeval's version

WinUI3

### Description of the problem

使用过不同方式登陆，在登陆后总是闪退

### Windows major version

Windows 11

**Comment by chanmaoganda** [comment]
很诡异，过一会自动好了。。。

**Comment by Poker-sang** [comment]
可以在设置看看，日志里写是什么原因导致的

**Comment by chanmaoganda** [comment]
11:41:52 Error
External component has thrown an exception.
at RegisterUnhandledExceptionHandler at C:\WorkSpace\Pixeval\src\Pixeval\App.xaml.cs: 136
	Type: System.Runtime.InteropServices.SEHException
	Source: Bypass
	Message: External component has thrown an exception.
	StackTrace: 
		   at Pixeval.Bypass.Injector.Inject(UInt32 pid, String payloadPath)
		   at Pixeval.Pages.Login.LoginPageViewModel.BrowserLogin()
		   at Pixeval.Pages.Login.LoginPage.BrowserLogin_OnClicked(Object sender, RoutedEventArgs e)
		   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
		   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)

11:46:03 Error
External component has thrown an exception.
at RegisterUnhandledExceptionHandler at C:\WorkSpace\Pixeval\src\Pixeval\App.xaml.cs: 136
	Type: System.Runtime.InteropServices.SEHException
	Source: Bypass
	Message: External component has thrown an exception.
	StackTrace: 
		   at Pixeval.Bypass.Injector.Inject(UInt32 pid, String payloadPath)
		   at Pixeval.Pages.Login.LoginPageViewModel.BrowserLogin()
		   at Pixeval.Pages.Login.LoginPage.BrowserLogin_OnClicked(Object sender, RoutedEventArgs e)
		   at WinRT._EventSource_global__Microsoft_UI_Xaml_RoutedEventHandler.EventState.<GetEventInvoke>b__1_0(Object sender, RoutedEventArgs e)
		   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)

11:46:21 Critical
UnhandledException
at RegisterUnhandledExceptionHandler at C:\WorkSpace\Pixeval\src\Pixeval\App.xaml.cs: 157
	Type: System.Net.Http.HttpRequestException
	Source: System.Net.Http
	Message: Response status code does not indicate success: 400 (Bad Request).
	StackTrace: 
		   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
		   at Pixeval.Pages.Login.PixivAuth.AuthCodeToSessionAsync(String code, String verifier)
		   at Pixeval.Activation.ActivationRegistrar.Dispatch(AppActivationArguments args)
		   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
		   at System.Threading.ThreadPoolWorkQueue.Dispatch()
		   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

11:47:22 Critical
UnhandledException
at RegisterUnhandledExceptionHandler at C:\WorkSpace\Pixeval\src\Pixeval\App.xaml.cs: 157
	Type: System.Net.Http.HttpRequestException
	Source: System.Net.Http
	Message: Response status code does not indicate success: 400 (Bad Request).
	StackTrace: 
		   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
		   at Pixeval.Pages.Login.PixivAuth.AuthCodeToSessionAsync(String code, String verifier)
		   at Pixeval.Activation.ActivationRegistrar.Dispatch(AppActivationArguments args)
		   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
		   at System.Threading.ThreadPoolWorkQueue.Dispatch()
		   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
